name: CI

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  style:
    name: Check basic style
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: LukasKalbertodt/check-basic-style@v0.1
      with:
        files: '**/!(*.md|*.json)'

  check:
    name: 'Build & test'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: cargo build
    - run: cargo test
    - run: cargo doc
